# Generated by Django 4.2.7 on 2024-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("active", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
