# Generated by Django 4.2.7 on 2024-10-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InitialQuestions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
