# Generated by Django 4.2.7 on 2024-07-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userilm_delete_emailverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userilm",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userilm",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userilm",
            name="last_name",
        ),
    ]
