# Generated by Django 4.2.7 on 2023-12-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fetchQuran", "0002_delete_projecttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("number_of_verses", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse_number", models.IntegerField()),
                ("arabic_text", models.TextField()),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="fetchQuran.surah",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerseTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=30)),
                ("text", models.TextField()),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="fetchQuran.verse",
                    ),
                ),
            ],
            options={
                "unique_together": {("verse", "language")},
            },
        ),
    ]
