# Generated by Django 4.2.7 on 2023-12-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0006_remove_surah_name_remove_surah_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verse",
            name="arabic_text",
        ),
        migrations.RemoveField(
            model_name="verse",
            name="verse_number",
        ),
        migrations.AddField(
            model_name="verse",
            name="text_uthmani",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="verse",
            name="verse_key",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="verse",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="verse",
            name="surah",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="fetchQuran.surah",
            ),
        ),
    ]
