# Generated by Django 4.2.7 on 2023-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fetchQuran",
            "0007_remove_verse_arabic_text_remove_verse_verse_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="glyph",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
