# Generated by Django 4.2.7 on 2023-12-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0008_verse_glyph"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verse",
            old_name="glyph",
            new_name="glyph_code",
        ),
    ]
