# Generated by Django 4.2.7 on 2023-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0009_rename_glyph_verse_glyph_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="glyph_code",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
