# Generated by Django 4.2.7 on 2023-12-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0010_alter_verse_glyph_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="versetranslation",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="versetranslation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="versetranslation",
            name="language",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="versetranslation",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="versetranslation",
            name="verse",
            field=models.ForeignKey(
                default=models.AutoField(primary_key=True, serialize=False),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="fetchQuran.verse",
            ),
        ),
    ]
