# Generated by Django 4.2.7 on 2023-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fetchQuran",
            "0011_versetranslation_author_alter_versetranslation_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="references",
            field=models.ManyToManyField(
                default="", related_name="verses", to="fetchQuran.verse"
            ),
        ),
    ]
