# Generated by Django 4.2.7 on 2023-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0013_remove_message_references_message_references"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="references",
            field=models.JSONField(default="default"),
        ),
    ]
