# Generated by Django 4.2.7 on 2023-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0016_alter_message_references"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="references",
            field=models.JSONField(null=True),
        ),
    ]
