# Generated by Django 4.2.7 on 2024-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0018_alter_message_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="recitation",
            field=models.FileField(null=True, upload_to="Recitation/"),
        ),
    ]
