# Generated by Django 4.2.7 on 2024-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0019_verse_recitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="recitation",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
