# Generated by Django 4.2.7 on 2024-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0020_alter_verse_recitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HadithTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=50)),
                ("bookNumber", models.CharField(max_length=20)),
                ("babID", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "englishBabNumber",
                    models.CharField(blank=True, max_length=21, null=True),
                ),
                (
                    "arabicBabNumber",
                    models.CharField(blank=True, max_length=21, null=True),
                ),
                ("hadithNumber", models.CharField(max_length=50)),
                ("ourHadithNumber", models.IntegerField()),
                ("arabicURN", models.IntegerField(unique=True)),
                ("arabicBabName", models.TextField(blank=True, null=True)),
                ("arabicText", models.TextField(blank=True, null=True)),
                ("arabicgrade1", models.CharField(max_length=2000)),
                ("englishURN", models.IntegerField(unique=True)),
                ("englishBabName", models.TextField(blank=True, null=True)),
                ("englishText", models.TextField(blank=True, null=True)),
                ("englishgrade1", models.CharField(max_length=2000)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("xrefs", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "HadithTable",
                "unique_together": {
                    ("arabicURN", "englishURN"),
                    ("collection", "bookNumber"),
                },
            },
        ),
    ]
