# Generated by Django 4.2.7 on 2024-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0021_hadithtable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HadithTable",
        ),
        migrations.AddField(
            model_name="chat",
            name="stream_id",
            field=models.CharField(default="", max_length=128),
        ),
    ]
