# Generated by Django 4.2.7 on 2024-07-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0022_delete_hadithtable_chat_stream_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="stream_id",
            new_name="thread_id",
        ),
    ]
