# Generated by Django 4.2.7 on 2024-07-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchQuran", "0023_rename_stream_id_chat_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
